# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bookchef"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Snitko"]
  s.date = "2013-09-10"
  s.email = "roman.snitko@gmail.com"
  s.executables = ["bookchef", "bookchef"]
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "bin/bookchef",
    "lib/bookchef.rb",
    "lib/bookchef/compilers/html.rb",
    "lib/bookchef/compilers/pdf.rb",
    "lib/bookchef/images/article_link.png",
    "lib/bookchef/images/book_link.png",
    "lib/bookchef/images/external_link.png",
    "lib/bookchef/images/lib_link.png",
    "lib/bookchef/images/manual_link.png",
    "lib/bookchef/images/video_link.png",
    "lib/bookchef/images/website_link.png",
    "lib/bookchef/stylesheets/css/default.css",
    "lib/bookchef/stylesheets/scss/default.scss",
    "lib/bookchef/stylesheets/xslt/bookchef_to_html.xsl",
    "lib/bookchef/templates/footer.html",
    "lib/bookchef/tree_merger.rb",
    "spec/fixtures/book/html_expected.html",
    "spec/fixtures/book/main.xml",
    "spec/fixtures/book/merge_expected.xml",
    "spec/fixtures/book/section1/index.xml",
    "spec/fixtures/book/section1/subsection.xml",
    "spec/fixtures/book/section1/supersubsection/hello.xml",
    "spec/fixtures/book/section1/supersubsection/index.xml",
    "spec/fixtures/book/settings.xml",
    "spec/lib/bookchef/compilers/html_spec.rb",
    "spec/lib/bookchef/tree_merger_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/snitko/bookchef"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Parser and compiler for BookChef.xml format"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pdfkit>, ["= 0.5.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<sass>, [">= 0"])
      s.add_development_dependency(%q<equivalent-xml>, [">= 0"])
      s.add_development_dependency(%q<nokogiri-diff>, [">= 0"])
    else
      s.add_dependency(%q<pdfkit>, ["= 0.5.0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<ruby-xslt>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<equivalent-xml>, [">= 0"])
      s.add_dependency(%q<nokogiri-diff>, [">= 0"])
    end
  else
    s.add_dependency(%q<pdfkit>, ["= 0.5.0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<ruby-xslt>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<equivalent-xml>, [">= 0"])
    s.add_dependency(%q<nokogiri-diff>, [">= 0"])
  end
end

